apiVersion: v1
kind: Service
metadata:
  name: lts-smp-api-dev-app-svc
  labels:
    app: lts-smp-api-dev
    tier: app
    version: v1
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: lts-smp-api-dev
    tier: app
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lts-smp-api-dev-app-dep
  labels:
    app: lts-smp-api-dev
    tier: app
    version: v1
spec:
  selector:
    matchLabels:
      app: lts-smp-api-dev
      tier: app
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: lts-smp-api-dev
        tier: app
        version: v1
    spec:
      containers:
        - name: lets-importation-api
          image: letsimportationapi:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
